community-tags:
  - Apache Avro
  - Apache Parquet
  - Apache ORC
  - Cloud Storage Systems
  - Open Source
  - GitHub
community-project-name: Cloud Storage Extension
community-project-description: |
  The [Exasol Cloud Storage Extension](https://github.com/exasol/cloud-storage-extension) for
  accessing formatted data Avro, Orc and Parquet, on public cloud storage systems.
